# Generated by Django 3.1.6 on 2021-02-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_superuser_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuser',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
