# Generated by Django 3.1.6 on 2021-03-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210224_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='b_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
