# Generated by Django 3.1.6 on 2021-03-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_superuser_b_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuser',
            name='b_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='buses_qr'),
        ),
    ]
