# Generated by Django 3.1.6 on 2021-03-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210321_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superuser',
            name='b_qr_code',
        ),
        migrations.AddField(
            model_name='superuser',
            name='cash_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
