# Generated by Django 3.1.6 on 2021-04-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210323_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superuser',
            name='cash_amount',
        ),
        migrations.AddField(
            model_name='superuser',
            name='cash',
            field=models.IntegerField(default=100),
        ),
    ]
