# Generated by Django 3.1.6 on 2021-04-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210405_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuser',
            name='cash',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
