# Generated by Django 3.1.6 on 2021-04-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210405_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='captain',
            field=models.BooleanField(default=False),
        ),
    ]
