# Generated by Django 3.1.6 on 2021-04-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_superuser_captain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superuser',
            name='qr_code',
        ),
    ]
