# Generated by Django 3.1.6 on 2021-05-11 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_superuser_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superuser',
            old_name='captain',
            new_name='driver',
        ),
        migrations.RemoveField(
            model_name='superuser',
            name='is_staff',
        ),
    ]
