# Generated by Django 3.1.6 on 2021-04-15 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('tprice', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('start_time', models.CharField(max_length=1000, null=True)),
                ('end_time', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Busstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('location_long', models.CharField(default=45.4215, max_length=1000, null=True)),
                ('location_lat', models.CharField(default=45.4215, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('qr_code', models.ImageField(upload_to='buses_qr')),
                ('bus', models.ManyToManyField(related_name='seat', to='bus.Buses')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='buses',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.busstation'),
        ),
    ]
