# Generated by Django 3.1.6 on 2021-04-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='destination',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
