# Generated by Django 3.1.6 on 2021-05-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_auto_20210519_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buses',
            old_name='total_price',
            new_name='tprice',
        ),
    ]
