# Generated by Django 3.1.6 on 2021-06-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_auto_20210615_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_sensor',
            name='date_time',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='p_sensor',
            name='pass_count',
            field=models.IntegerField(),
        ),
    ]
