# Generated by Django 3.1.6 on 2021-06-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0009_tracking_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='time',
            field=models.CharField(max_length=300),
        ),
    ]
