# Generated by Django 3.1.6 on 2021-06-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0010_auto_20210616_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='lat',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='long',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='timestamp',
            field=models.CharField(max_length=300),
        ),
    ]
